-module(morse_beep_practice).

-export([
    listen/2
]).

-export_type([
    mode/0
]).

-type mode() :: char | word | sentence.

-spec listen(mode(), morse_beep:options()) -> no_return().
listen(Mode, Opts) ->
    Question = question(Mode),
    morse_beep:await(Question, Opts),
    Answer = klsn_io:get_line(),
    case Question =:= Answer of
        true ->
            os:cmd("beep -f 4000 -l 100 -D 100 -n -f 3200 -l 300");
        false ->
            os:cmd("beep -f 320 -l 100 -D 100 -n -f 320 -l 300")
    end,
    klsn_io:format("~ts~n", [Question]),
    listen(Mode, Opts).

question(Mode) ->
    List = question_list(Mode),
    Index = rand:uniform(length(List)),
    lists:nth(Index, List).

question(char) ->
    [
        <<"a\n">>,
        <<"b\n">>
    ];
question(word) ->
    [
        <<"sos\n">>,
        <<"hello\n">>,
        <<"world\n">>,
        <<"morse\n">>,
        <<"code\n">>,
        <<"signal\n">>,
        <<"beep\n">>,
        <<"error\n">>,
        <<"urgent\n">>,
        <<"response\n">>,
        <<"transmit\n">>,
        <<"frequency\n">>,
        <<"receiver\n">>,
        <<"transmitter\n">>,
        <<"communication\n">>,
        <<"emergency\n">>,
        <<"timing\n">>,
        <<"pattern\n">>,
        <<"dah\n">>,
        <<"dit\n">>,
        <<"space\n">>,
        <<"repeat\n">>,
        <<"attention\n">>,
        <<"message\n">>,
        <<"letter\n">>,
        <<"word\n">>,
        <<"numeric\n">>,
        <<"character\n">>,
        <<"decode\n">>,
        <<"encode\n">>,
        <<"speed\n">>,
        <<"accuracy\n">>,
        <<"operator\n">>,
        <<"clarity\n">>,
        <<"tone\n">>,
        <<"array\n">>,
        <<"broadcast\n">>,
        <<"listen\n">>,
        <<"switch\n">>,
        <<"feedback\n">>,
        <<"network\n">>,
        <<"control\n">>,
        <<"protocol\n">>,
        <<"manual\n">>,
        <<"automatic\n">>,
        <<"command\n">>,
        <<"instruction\n">>,
        <<"channel\n">>,
        <<"transmission\n">>,
        <<"reception\n">>,
        <<"adjust\n">>,
        <<"amplify\n">>,
        <<"modulate\n">>,
        <<"demodulate\n">>,
        <<"oscillator\n">>,
        <<"battery\n">>,
        <<"current\n">>,
        <<"voltage\n">>,
        <<"resistor\n">>,
        <<"capacitor\n">>,
        <<"inductor\n">>,
        <<"circuit\n">>,
        <<"device\n">>,
        <<"module\n">>,
        <<"system\n">>,
        <<"source\n">>,
        <<"destination\n">>,
        <<"wavelength\n">>,
        <<"antenna\n">>,
        <<"efficiency\n">>,
        <<"static\n">>,
        <<"dynamic\n">>,
        <<"interface\n">>,
        <<"monitor\n">>,
        <<"digit\n">>,
        <<"dash\n">>,
        <<"dot\n">>,
        <<"break\n">>,
        <<"temporary\n">>,
        <<"clear\n">>,
        <<"test\n">>,
        <<"verify\n">>,
        <<"learn\n">>,
        <<"skill\n">>,
        <<"mastery\n">>,
        <<"adjustment\n">>,
        <<"binary\n">>,
        <<"signalize\n">>,
        <<"channeling\n">>,
        <<"encryption\n">>,
        <<"decryption\n">>,
        <<"synchrony\n">>,
        <<"protocols\n">>,
        <<"operational\n">>,
        <<"transceiver\n">>,
        <<"regulate\n">>,
        <<"amplitude\n">>,
        <<"continuity\n">>,
        <<"variation\n">>,
        <<"stability\n">>
    ];
question(sentence) ->
    [
        <<"The quick brown fox jumps over the lazy dog\n">>,
        <<"Morse code is a beautiful method of communication\n">>,
        <<"Erlang programming provides fault tolerance\n">>,
        <<"Practice makes perfect in digital communication\n">>,
        <<"Listening carefully improves code comprehension\n">>,
        <<"The operator adjusts the frequency with precision\n">>,
        <<"Errors in transmission can be frustrating\n">>,
        <<"Always verify your code for consistency\n">>,
        <<"Communication signals require clear patterns\n">>,
        <<"Sound beeps indicate success or failure\n">>,
        <<"The message was sent in a secure channel\n">>,
        <<"Timely responses are critical in emergencies\n">>,
        <<"Learning Morse code can be both fun and challenging\n">>,
        <<"A well-tuned system outperforms outdated hardware\n">>,
        <<"Transmit the signal with confidence and clarity\n">>,
        <<"The receiver picks up every detailed tone\n">>,
        <<"Accurate decoding leads to effective communication\n">>,
        <<"Each element must be adjusted for optimum performance\n">>,
        <<"Advanced encryption protects sensitive information\n">>,
        <<"A simple beep can convey complex messages\n">>,
        <<"Timely adjustments enhance communication quality\n">>,
        <<"Clear instructions lead to efficient operations\n">>,
        <<"Synchronization in transmissions prevents delays\n">>,
        <<"High frequency signals travel faster than expected\n">>,
        <<"Robust protocols ensure reliable connections\n">>,
        <<"The operator listens to every subtle error\n">>,
        <<"Real-time feedback is essential in control systems\n">>,
        <<"Consistent practice builds communication skills\n">>,
        <<"Every puzzle has a solution in its pattern\n">>,
        <<"The system maintains stability amidst turbulence\n">>,
        <<"Digital signals create endless possibilities\n">>,
        <<"Morse code has a rich history in communication\n">>,
        <<"Effective modulation boosts signal strength\n">>,
        <<"New protocols are developed every day\n">>,
        <<"There is a perfect balance between speed and accuracy\n">>,
        <<"The device operates on a strict timing schedule\n">>,
        <<"Efficient algorithms improve reception quality\n">>,
        <<"Careful tuning minimizes transmission errors\n">>,
        <<"The beep indicates that the test was successful\n">>,
        <<"Regular updates keep the network running smoothly\n">>,
        <<"Familiarity with patterns enhances learning\n">>,
        <<"Practice helps overcome challenges in coding\n">>,
        <<"Even a small error can disrupt communication\n">>,
        <<"The transmitter sends crisp and clear signals\n">>,
        <<"Reliable devices are the backbone of networks\n">>,
        <<"Every call for help is answered promptly\n">>,
        <<"Digital and analog modes offer diverse experiences\n">>,
        <<"Operator expertise ensures timely responses\n">>,
        <<"The channel remained open for continuous communication\n">>,
        <<"Quick adjustments lead to efficient outcomes\n">>,
        <<"Lessons in Morse code open a window to history\n">>,
        <<"Robust systems require constant maintenance\n">>,
        <<"The sender repeats the message for added clarity\n">>,
        <<"Every signal depends on precise modulation techniques\n">>,
        <<"Long-distance communication depends on system stability\n">>,
        <<"The operator monitors every transmission carefully\n">>,
        <<"Our network adapts to challenging conditions\n">>,
        <<"Decoding signals is both an art and a science\n">>,
        <<"Complex problems can be solved with teamwork and persistence\n">>,
        <<"Innovative technology drives progress in communication methods\n">>,
        <<"Rapid signals require precise timing adjustments\n">>,
        <<"A clear pattern is a sign of effective transmission\n">>,
        <<"A well-calibrated system prevents communication confusion\n">>,
        <<"Transmission delays can impact overall performance\n">>,
        <<"Accuracy in decoding is key to understanding messages\n">>,
        <<"System stability is essential for continuous operations\n">>,
        <<"The beep serves as a confirmation sound during tests\n">>,
        <<"Quality channels improve overall signal integrity\n">>,
        <<"Robust mechanisms protect the network against interruptions\n">>,
        <<"Every beep carries vital information for operators\n">>,
        <<"Listening carefully can reveal hidden transmission patterns\n">>,
        <<"Consistent practice refines Morse code skills remarkably\n">>,
        <<"Technology continuously evolves with innovative methods\n">>,
        <<"The art of coding is marked by persistence and creativity\n">>,
        <<"Digital decoding requires both logic and imagination\n">>,
        <<"Testing different communication modes improves adaptability\n">>,
        <<"The operator adjusts controls with swift precision\n">>,
        <<"Complex codes become simple with dedicated practice\n">>,
        <<"Accuracy and timing are critical for successful transmissions\n">>,
        <<"Learning from mistakes is a vital part of growth\n">>,
        <<"Effective communication brings people together across distances\n">>,
        <<"Signals travel through an intricate network of pathways\n">>,
        <<"Integrity of the system depends on regular updates\n">>,
        <<"Every element in the code serves a unique purpose\n">>,
        <<"Smooth operations demand rigorous testing and maintenance\n">>,
        <<"Continuous improvement drives technological advances\n">>,
        <<"Reliable channels bridge vast geographical distances\n">>,
        <<"Attention to detail prevents costly transmission errors\n">>,
        <<"Collaboration among team members fosters innovative solutions\n">>,
        <<"The rhythm of Morse code is uniquely captivating and historic\n">>,
        <<"Technological mastery blends art seamlessly with science\n">>,
        <<"Precision in every beep sharpens overall communication\n">>,
        <<"The operator’s expertise transforms chaos into organized order\n">>,
        <<"Simple patterns can encode surprisingly complex messages\n">>,
        <<"Signal patterns form the language of effective transmissions\n">>,
        <<"Steady practice yields remarkable improvements in skill\n">>,
        <<"Innovative thinking enhances overall system performance\n">>,
        <<"Every challenge is an opportunity to learn and grow\n">>,
        <<"Mastery of coding leads to seamless and efficient communication\n">>,
        <<"The future belongs to those who dare to innovate boldly\n">>
    ].
