-module(morse_beep_practice).

-export([
    listen/2
]).

-export_type([
    mode/0
]).

-type mode() :: char | word | sentence.

-spec listen(mode(), morse_beep:options()) -> no_return().
listen(Mode, Opts) ->
    Question = question(Mode),
    morse_beep:await(Question, Opts),
    Answer = klsn_io:get_line(),
    case Question =:= Answer of
        true ->
            os:cmd("beep -f 4000 -l 100 -D 100 -n -f 3200 -l 300");
        false ->
            os:cmd("beep -f 320 -l 100 -D 100 -n -f 320 -l 300")
    end,
    klsn_io:format("~ts~n", [Question]),
    listen(Mode, Opts).

question(Mode) ->
    List = question_list(Mode),
    Index = rand:uniform(length(List)),
    lists:nth(Index, List).

question(char) ->
    [
        <<"a\n">>,
        <<"b\n">>
    ];
question(word) ->
    [
        <<"Word number 1\n">>,
        <<"Word number 2\n">>,
        <<"Word number 3\n">>,
        <<"Word number 4\n">>,
        <<"Word number 5\n">>,
        <<"Word number 6\n">>,
        <<"Word number 7\n">>,
        <<"Word number 8\n">>,
        <<"Word number 9\n">>,
        <<"Word number 10\n">>,
        <<"Word number 11\n">>,
        <<"Word number 12\n">>,
        <<"Word number 13\n">>,
        <<"Word number 14\n">>,
        <<"Word number 15\n">>,
        <<"Word number 16\n">>,
        <<"Word number 17\n">>,
        <<"Word number 18\n">>,
        <<"Word number 19\n">>,
        <<"Word number 20\n">>,
        <<"Word number 21\n">>,
        <<"Word number 22\n">>,
        <<"Word number 23\n">>,
        <<"Word number 24\n">>,
        <<"Word number 25\n">>,
        <<"Word number 26\n">>,
        <<"Word number 27\n">>,
        <<"Word number 28\n">>,
        <<"Word number 29\n">>,
        <<"Word number 30\n">>,
        <<"Word number 31\n">>,
        <<"Word number 32\n">>,
        <<"Word number 33\n">>,
        <<"Word number 34\n">>,
        <<"Word number 35\n">>,
        <<"Word number 36\n">>,
        <<"Word number 37\n">>,
        <<"Word number 38\n">>,
        <<"Word number 39\n">>,
        <<"Word number 40\n">>,
        <<"Word number 41\n">>,
        <<"Word number 42\n">>,
        <<"Word number 43\n">>,
        <<"Word number 44\n">>,
        <<"Word number 45\n">>,
        <<"Word number 46\n">>,
        <<"Word number 47\n">>,
        <<"Word number 48\n">>,
        <<"Word number 49\n">>,
        <<"Word number 50\n">>,
        <<"Word number 51\n">>,
        <<"Word number 52\n">>,
        <<"Word number 53\n">>,
        <<"Word number 54\n">>,
        <<"Word number 55\n">>,
        <<"Word number 56\n">>,
        <<"Word number 57\n">>,
        <<"Word number 58\n">>,
        <<"Word number 59\n">>,
        <<"Word number 60\n">>,
        <<"Word number 61\n">>,
        <<"Word number 62\n">>,
        <<"Word number 63\n">>,
        <<"Word number 64\n">>,
        <<"Word number 65\n">>,
        <<"Word number 66\n">>,
        <<"Word number 67\n">>,
        <<"Word number 68\n">>,
        <<"Word number 69\n">>,
        <<"Word number 70\n">>,
        <<"Word number 71\n">>,
        <<"Word number 72\n">>,
        <<"Word number 73\n">>,
        <<"Word number 74\n">>,
        <<"Word number 75\n">>,
        <<"Word number 76\n">>,
        <<"Word number 77\n">>,
        <<"Word number 78\n">>,
        <<"Word number 79\n">>,
        <<"Word number 80\n">>,
        <<"Word number 81\n">>,
        <<"Word number 82\n">>,
        <<"Word number 83\n">>,
        <<"Word number 84\n">>,
        <<"Word number 85\n">>,
        <<"Word number 86\n">>,
        <<"Word number 87\n">>,
        <<"Word number 88\n">>,
        <<"Word number 89\n">>,
        <<"Word number 90\n">>,
        <<"Word number 91\n">>,
        <<"Word number 92\n">>,
        <<"Word number 93\n">>,
        <<"Word number 94\n">>,
        <<"Word number 95\n">>,
        <<"Word number 96\n">>,
        <<"Word number 97\n">>,
        <<"Word number 98\n">>,
        <<"Word number 99\n">>,
        <<"Word number 100\n">>
    ];
question(sentence) ->
    [
        <<"This is sentence 1\n">>,
        <<"This is sentence 2\n">>,
        <<"This is sentence 3\n">>,
        <<"This is sentence 4\n">>,
        <<"This is sentence 5\n">>,
        <<"This is sentence 6\n">>,
        <<"This is sentence 7\n">>,
        <<"This is sentence 8\n">>,
        <<"This is sentence 9\n">>,
        <<"This is sentence 10\n">>,
        <<"This is sentence 11\n">>,
        <<"This is sentence 12\n">>,
        <<"This is sentence 13\n">>,
        <<"This is sentence 14\n">>,
        <<"This is sentence 15\n">>,
        <<"This is sentence 16\n">>,
        <<"This is sentence 17\n">>,
        <<"This is sentence 18\n">>,
        <<"This is sentence 19\n">>,
        <<"This is sentence 20\n">>,
        <<"This is sentence 21\n">>,
        <<"This is sentence 22\n">>,
        <<"This is sentence 23\n">>,
        <<"This is sentence 24\n">>,
        <<"This is sentence 25\n">>,
        <<"This is sentence 26\n">>,
        <<"This is sentence 27\n">>,
        <<"This is sentence 28\n">>,
        <<"This is sentence 29\n">>,
        <<"This is sentence 30\n">>,
        <<"This is sentence 31\n">>,
        <<"This is sentence 32\n">>,
        <<"This is sentence 33\n">>,
        <<"This is sentence 34\n">>,
        <<"This is sentence 35\n">>,
        <<"This is sentence 36\n">>,
        <<"This is sentence 37\n">>,
        <<"This is sentence 38\n">>,
        <<"This is sentence 39\n">>,
        <<"This is sentence 40\n">>,
        <<"This is sentence 41\n">>,
        <<"This is sentence 42\n">>,
        <<"This is sentence 43\n">>,
        <<"This is sentence 44\n">>,
        <<"This is sentence 45\n">>,
        <<"This is sentence 46\n">>,
        <<"This is sentence 47\n">>,
        <<"This is sentence 48\n">>,
        <<"This is sentence 49\n">>,
        <<"This is sentence 50\n">>,
        <<"This is sentence 51\n">>,
        <<"This is sentence 52\n">>,
        <<"This is sentence 53\n">>,
        <<"This is sentence 54\n">>,
        <<"This is sentence 55\n">>,
        <<"This is sentence 56\n">>,
        <<"This is sentence 57\n">>,
        <<"This is sentence 58\n">>,
        <<"This is sentence 59\n">>,
        <<"This is sentence 60\n">>,
        <<"This is sentence 61\n">>,
        <<"This is sentence 62\n">>,
        <<"This is sentence 63\n">>,
        <<"This is sentence 64\n">>,
        <<"This is sentence 65\n">>,
        <<"This is sentence 66\n">>,
        <<"This is sentence 67\n">>,
        <<"This is sentence 68\n">>,
        <<"This is sentence 69\n">>,
        <<"This is sentence 70\n">>,
        <<"This is sentence 71\n">>,
        <<"This is sentence 72\n">>,
        <<"This is sentence 73\n">>,
        <<"This is sentence 74\n">>,
        <<"This is sentence 75\n">>,
        <<"This is sentence 76\n">>,
        <<"This is sentence 77\n">>,
        <<"This is sentence 78\n">>,
        <<"This is sentence 79\n">>,
        <<"This is sentence 80\n">>,
        <<"This is sentence 81\n">>,
        <<"This is sentence 82\n">>,
        <<"This is sentence 83\n">>,
        <<"This is sentence 84\n">>,
        <<"This is sentence 85\n">>,
        <<"This is sentence 86\n">>,
        <<"This is sentence 87\n">>,
        <<"This is sentence 88\n">>,
        <<"This is sentence 89\n">>,
        <<"This is sentence 90\n">>,
        <<"This is sentence 91\n">>,
        <<"This is sentence 92\n">>,
        <<"This is sentence 93\n">>,
        <<"This is sentence 94\n">>,
        <<"This is sentence 95\n">>,
        <<"This is sentence 96\n">>,
        <<"This is sentence 97\n">>,
        <<"This is sentence 98\n">>,
        <<"This is sentence 99\n">>,
        <<"This is sentence 100\n">>
    ].
